repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
  #    - id: debug-statements
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/psf/black
  #   rev: 20.8b1
  #   hooks:
  #     - id: black
  #       language_version: python3
  #       args:
  #         - "{{cookiecutter.profile_name}}/slurm-submit.py"
  #         - "{{cookiecutter.profile_name}}/slurm_utils.py"
  #         - tests/wrapper.py
  #         - tests/test_slurm.py
  #         - tests/test_slurm_advanced.py
  #         - tests/test_cookie.py
  #       exclude: ^\{\{cookiecutter.profile_name\}\}
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.8.3
  #   hooks:
  #     - id: flake8
  #       args: [--config=.flake8]
  #       additional_dependencies: ["flake8-bugbear==20.1.4", "flake8-builtins==1.5.2"]
