# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

sudo: required
dist: trusty

language: python

python:
  - "3.5"
  - "3.6"

services:
  - docker

before_install:
  - docker pull giovtorres/docker-centos7-slurm:latest
  - docker pull quay.io/biocontainers/snakemake:4.6.0--py35_0
  - docker pull quay.io/biocontainers/snakemake:4.6.0--py36_0

install:
  - pip install -r requirements.txt

script:
  - pytest -v -s
