# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working-directory: ~/cookiecutter-slurm
    machine: true
    steps:
      - checkout
      - run:
          name: Update PATH
          command: echo 'export PATH="`pwd`/miniconda/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Setup Conda
          command: .circleci/setup.sh
      Download and cache dependencies
      - restore_cache:
          keys:
            - snakemake-profiles-slurm-{{ checksum "requirements.txt" }}
      - run:
          name: Setup slurm container
          command: docker pull giovtorres/docker-centos7-slurm:latest
      - run:
          name: Setup snakemake container
          command: docker pull quay.io/biocontainers/snakemake:5.3.0--py36_1
      - run:
          name: Initialize docker swarm
          command: docker swarm init
      - run:
          name: Install test dependencies
          command: pip install -r requirements.txt
      - save_cache:
          key: snakemake-profiles-slurm-{{ checksum "requirements.txt" }}
          paths:
            - miniconda
      - run:
          name: Run tests
          no_output_timeout: 30m
          command: pytest -v -s --tb=no
      - store_artifacts:
          path: test-reports
          destination: test-reports
